env:
  browser: true
extends:
  - ../../.eslintrc.react.yml
rules:
  react/no-deprecated: off

  # Disable for convenience
  react/display-name: off
  # Disable for convenience
  react/prop-types: off
