extends:
  - ./.eslintrc.custom.yml
ignorePatterns:
  - test/**/dist/**
  - test/webDriver/static/**
overrides:
  - env:
      commonjs: true
    files:
      - '**/*.js'
  - files:
      - '**/*.mjs'
    parserOptions:
      ecmaVersion: latest
      sourceType: module
