version: '3'
services:
  chromium:
    depends_on:
      - hub
    environment:
      SE_ENABLE_TRACING: false
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_SESSION_TIMEOUT: 5
    image: selenium/node-chromium:130.0
    shm_size: 2gb
    stop_grace_period: 0s
    volumes:
      - /dev/shm:/dev/shm

  hub:
    environment:
      GRID_TIMEOUT: 5
      SE_ENABLE_TRACING: false
    image: selenium/hub:4
    ports:
      - "4444:4444"
    stop_grace_period: 0s

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    stop_grace_period: 0s
    volumes:
      - ./test/webDriver:/usr/share/nginx/html:ro
